const SPECIAL_DRINKS = {
    spirits: [{
        "nr": "1241808",
        "artikelid": "41013",
        "varnummer": "12418",
        "namn": "Inycon",
        "namn2": "Chardonnay",
        "prisinklmoms": "229.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2003-10-06",
        "slutlev": " ",
        "varugrupp": "Vitt vin",
        "forpackning": "Box",
        "forslutning": "Vingtapp",
        "ursprung": "Sicilien",
        "ursprunglandnamn": "Italien",
        "producent": "Inycon Estate",
        "leverantor": "Nigab",
        "argang": "2012",
        "provadargang": "2012",
        "alkoholhalt": "13%",
        "modul": "",
        "sortiment": "BS",
        "ekologisk": "0",
        "koscher": "0",
        "vip": true,
    }, {
        "nr": "1241901",
        "artikelid": "10900",
        "varnummer": "12419",
        "namn": "Casal di Serra",
        "namn2": "Classico Superiore",
        "prisinklmoms": "79.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1996-08-05",
        "slutlev": " ",
        "varugrupp": "Vitt vin,  Friskt & Fruktigt",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "Marche, Verdicchio dei Castelli di Jesi",
        "ursprunglandnamn": "Italien",
        "producent": "Umani Ronchi",
        "leverantor": "Enjoy Wine & Spirits AB",
        "argang": "2013",
        "provadargang": "2013",
        "alkoholhalt": "13%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "vip": true,
    }, {
        "nr": "1243401",
        "artikelid": "12583",
        "varnummer": "12434",
        "namn": "Lambrusco dell'Emilia",
        "namn2": "Bianco",
        "prisinklmoms": "50.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "1997-01-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin,  Druvigt & Blommigt",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Emilia-Romagna, Lambrusco dell'Emilia",
        "ursprunglandnamn": "Italien",
        "producent": "Donelli",
        "leverantor": "Enjoy Wine & Spirits AB",
        "argang": "2010",
        "provadargang": "2010",
        "alkoholhalt": "7%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "vip": true,
    }, {
        "nr": "1243801",
        "artikelid": "374079",
        "varnummer": "12438",
        "namn": "Pasqua",
        "namn2": "Chardonnay Grillo",
        "prisinklmoms": "59.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2009-04-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin,  Friskt & Fruktigt",
        "forpackning": "Flaska",
        "forslutning": "Skruvkapsyl",
        "ursprung": "Sicilien",
        "ursprunglandnamn": "Italien",
        "producent": "Pasqua",
        "leverantor": "Enjoy Wine & Spirits AB",
        "argang": "2013",
        "provadargang": "2013",
        "alkoholhalt": "13.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "1",
        "koscher": "0",
        "vip": true,
    }, {
        "nr": "124603",
        "artikelid": "805678",
        "varnummer": "1246",
        "namn": "Mikkeller",
        "namn2": "American Dream",
        "prisinklmoms": "19.90",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2014-03-01",
        "slutlev": " ",
        "varugrupp": "Öl, Ljus lager",
        "forpackning": "Flaska",
        "forslutning": "",
        "ursprung": "",
        "ursprunglandnamn": "Internationellt märke",
        "producent": "Mikkeller",
        "leverantor": "Brill & Co AB",
        "argang": "",
        "provadargang": "",
        "alkoholhalt": "4.6%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "0",
        "koscher": "0",
        "vip": true,
    }, {
        "nr": "1250202",
        "artikelid": "280100",
        "varnummer": "12502",
        "namn": "Fasoli Gino",
        "namn2": "Soave Borgoletto",
        "prisinklmoms": "59.00",
        "volymiml": null,
        "prisperliter": null,
        "saljstart": "2007-10-01",
        "slutlev": " ",
        "varugrupp": "Vitt vin,  Friskt & Fruktigt",
        "forpackning": "Flaska",
        "forslutning": "Naturkork",
        "ursprung": "Venetien, Soave",
        "ursprunglandnamn": "Italien",
        "producent": "Fasoli Gino",
        "leverantor": "Terrific Wines AB",
        "argang": "2013",
        "provadargang": "2013",
        "alkoholhalt": "12.5%",
        "modul": "",
        "sortiment": "FS",
        "ekologisk": "1",
        "koscher": "0",
        "vip": true,
    }],
};
